Fix missing brackets in scala-steward.conf
The missing brackets caused a fatal parsing exception on Scala Steward startup:

https://github.com/guardian/scala-steward-public-repos/actions/runs/11617262901/job/32352086260#step:7:47

```
2024-10-31 17:57:14,124 INFO  Loaded 35 Scalafix migration(s)
  Error: java.lang.Throwable: Failed to load repo config from common-config/scala-steward.conf
  Error: 	at org.scalasteward.core.repoconfig.RepoConfigLoader$$anonfun$decodeRepoConfig$1.applyOrElse(RepoConfigLoader.scala:50)
  Error: 	at org.scalasteward.core.repoconfig.RepoConfigLoader$$anonfun$decodeRepoConfig$1.applyOrElse(RepoConfigLoader.scala:50)
  Error: 	at scala.PartialFunction$AndThen.applyOrElse(PartialFunction.scala:288)
  Error: 	at cats.ApplicativeError.$anonfun$recoverWith$1(ApplicativeError.scala:172)
  Error: 	at adaptErr$extension @ org.scalasteward.core.update.artifact.ArtifactMigrationsLoader.decodeMigrations(ArtifactMigrationsLoader.scala:50)
  Error: 	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
  Error: 	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
  Error: 	at main$ @ org.scalasteward.core.Main$.main(Main.scala:23)
  Error: 	at flatMap @ org.scalasteward.core.repoconfig.RepoConfigLoader.$anonfun$loadRepoConfig$2(RepoConfigLoader.scala:46)
  Error: 	at delay @ org.typelevel.log4cats.slf4j.internal.Slf4jLoggerInternal$Slf4jLogger.isDebugEnabled(Slf4jLoggerInternal.scala:73)
  Error: Caused by: ParsingFailure: String: 19: expecting a close parentheses ')' here, not: '{'
```

I missed these brackets when making the config update in
https://github.com/guardian/scala-steward-public-repos/pull/77 - I was editing
the `scala-steward.conf` file using IntelliJ, and by default IntelliJ didn't have linting
checks for the HOCON format used by that file - it didn't even warn on mis-matched brackets!
However, there is an IntelliJ plugin for HOCON, and once I installed it IntelliJ did correctly
highlight errors:

* https://github.com/AVSystem/intellij-hocon
* https://plugins.jetbrains.com/plugin/10481-hocon